# Generated by Django 5.2.1 on 2025-05-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='Data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='Data_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professorgestor',
            name='Data_de_Nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professorgestor',
            name='Data_de_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
