# Generated by Django 5.2.1 on 2025-05-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ambiente_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorgestor',
            name='NI',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
