# Generated by Django 5.2.1 on 2025-05-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_professorgestor_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorgestor',
            name='NI',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
