# Generated by Django 5.2.1 on 2025-05-12 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_professorgestor_ni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='Sala_reservada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala'),
        ),
    ]
