# Generated by Django 5.2.1 on 2025-05-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sala_alter_ambiente_sala_reservada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='id',
        ),
        migrations.AddField(
            model_name='sala',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
