# Generated by Django 5.2.1 on 2025-05-12 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_sala_id_sala_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='Sala_reservada',
            field=models.ForeignKey(db_column='codigo', on_delete=django.db.models.deletion.CASCADE, to='app.sala'),
        ),
    ]
