# Generated by Django 5.2.1 on 2025-05-12 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_ambiente_sala_reservada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='Sala_reservada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala'),
        ),
    ]
