# Generated by Django 5.2.1 on 2025-05-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ambiente_sala_reservada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='codigo',
        ),
        migrations.AddField(
            model_name='sala',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
