# Generated by Django 5.2.1 on 2025-05-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_sala_codigo_sala_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorgestor',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
