# Generated by Django 5.2.1 on 2025-05-20 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_professorgestor_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='professor_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'Usuario': 'Professor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
