# Generated by Django 5.2.1 on 2025-05-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_sala_professor_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='professor_responsavel',
            new_name='Professor_responsavel',
        ),
    ]
