# Generated by Django 5.2.1 on 2025-05-22 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_professor_responsavel_sala_professor_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='professor_responsavel',
            field=models.ForeignKey(limit_choices_to={'Usuario': 'Professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
