# Generated by Django 5.2.1 on 2025-05-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_sala_professor_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='professor_responsavel',
        ),
    ]
