# Generated by Django 5.2.1 on 2025-05-22 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_sala_professor_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='Disciplina_professor',
            field=models.ForeignKey(default=1, limit_choices_to={'Usuario': 'Professor'}, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='Professor_responsavel',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to={'Usuario': 'Professor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
