# Generated by Django 5.2.1 on 2025-05-23 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_ambiente_disciplina_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='Disciplina_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplina'),
        ),
    ]
