# Generated by Django 5.2.1 on 2025-05-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_ambiente_disciplina_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='Carga_Horaria',
            field=models.CharField(max_length=10),
        ),
    ]
